# Header
menu:
  首页: /#blog
  关于: /about
  归档: /archive

# Site favicon
favicon: /favicon.ico

# Site logo
logo: /images/logo.jpg

# Enable Mathjax
mathjax: false

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false